### PR TITLE
Fix dlclose and plugins

### LINKED ISSUE #21: Singletons and plugins: dlclose affects singleton state
As described already in #7, the combo singleton plus plugins (plus python) is quite delicate. I am facing a very subtle problem when multiple environment are sequentially created in python in the same process. Take as example the following `pytest`, that creates 2 identical environments, overriding the first `env` variable and hence closing the resources of the first one:

```python
import gym
import gym_ignition
from gym_ignition.utils import logger


# Set gym verbosity
logger.set_level(gym.logger.WARN)


def test_create_cpp_environment():
     # Environment #1
    env = gym.make("CartPoleIgnition-v0")
    assert env, "Failed to create CartPoleIgnition-v0 environment"

    action = env.action_space.sample()
    assert isinstance(action, int), "The sampled action is empty"

    observation = env.observation_space.sample()
    assert observation.size > 0, "The sampled observation is empty"

    observation = env.reset()
    assert observation.size > 0, "The observation is empty"

    state, reward, done, _ = env.step(action)
    assert state.size > 0, "The environment didn't return a valid state"

    # Environment #2
    env = gym.make("CartPoleIgnition-v0")
    assert env, "Failed to create CartPoleIgnition-v0 environment"

    action = env.action_space.sample()
    assert isinstance(action, int), "The sampled action is empty"

    observation = env.observation_space.sample()
    assert observation.size > 0, "The sampled observation is empty"

    observation = env.reset()
    assert observation.size > 0, "The observation is empty"

    state, reward, done, _ = env.step(action)
    assert state.size > 0, "The environment didn't return a valid state"
```

In this case the system allocates two different `IgnitionEnvironment` objects containing the gazebo server, which under the hood `dlopen`s the same plugin library. This means that two instances of the plugin are loaded in the same time. Beyond this, there's a `EnvironmentCallbacksSingleton` object, contained in a shared library, that stores resources of the plugins.

It can be expected that the shared library containing the singleton stays loaded for the entire lifecycle of both plugins. However, when the first one is deleted, the `dlclose` also calls the singleton destructor (which is a very weird behavior, singleton should not be destroyed by design). This behaviour breaks the second environment, which is still alive, and the entire application segfaults. Worth to note is that this happens only in Release. The compilation in Debug is not affected by this behaviour.

**Solution:** Remove the pimpl pattern from the `EnvironmentCallbacksSingleton` such that the destructor can be called without causing harm, and preserve the state even after possible destructor call by converting all the private attributes to `static` (there's just one).

cc @traversaro Not sure if you want to add any detail, particularly about you investigation on `cxa_atexit`

### PR DESCRIPTION
**Pull request by diegoferigo**
Fixes #21

### CODE REVIEW

File: plugins/RobotController/RobotController.cpp [hunk 1]
```diff
@@ -38,6 +38,16 @@ RobotController::RobotController()
     , pImpl{new Impl(), [](Impl* impl) { delete impl; }}
 {}
 
+RobotController::~RobotController()
+{
+    auto* ecSingleton = EnvironmentCallbacksSingleton::Instance();
+
+    if (bool removed = ecSingleton->deleteEnvironmentCallback(pImpl->robot->name()); !removed) {
```
Comment (traversaro) [inline plugins/RobotController/RobotController.cpp]: There is any reason for not keeping `bool removed = ecSingleton->deleteEnvironmentCallback(pImpl->robot->name())` outside the `if` loop? In this way the code is a bit heard to read (to be honest I am just assuming what `if(a;b)` actually means, I do not know without checking.

Comment (diegoferigo) [reply plugins/RobotController/RobotController.cpp]: This is new C++17 syntax. Since we typically use this style of checking errors in an `if` statement and then omit the `else` for the code after the check, I prefer this syntax particularly when I collapse the code in the IDE. There's no external resource that leaks.

Just to understand, you don't like this `if` style, or you just are not used to it and it seems strange?

Comment (traversaro) [reply plugins/RobotController/RobotController.cpp]: > Just to understand, you don't like this if style, or you just are not used to it and it seems strange?

Definitely the second one, I  am just not used to it. Apparently it is also quite difficult to find info on that was also tricky to find resources on it, unless you know that this is C++17. On my machine, if I search on Google "semicolon inside if clause C++" beside cppreference I don't get any relevant result (I found something more relevant if I add C++17). However, it is just that developers need to get used to this, not an actual problem of the PR.
